- type: job
  id: ExpeditionDirector
  name: job-name-ExpeditionDirector
  description: job-description-ExpeditionDirector
  playTimeTracker: JobExpeditionDirector
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 14400 # 4 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 14400 # 4 hours
    - !type:DepartmentTimeRequirement
      department: Science
      time: 14400 # 4 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 14400 # 4 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 14400 # 4 hours
      #any MRP using our code might eventually want to use it
    # - !type:SaturationRequirement # MisandryBox - no neon hair on captain
    #   hairColorSaturation: 0.30
  #goobcoins: 50 #Goob content Corvax-Goob-coins
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconExpeditionDirector"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Condemned # Goobstation - Nanotrasen owns your soul pal.
        soulOwnedNotDevil: true
      - type: Skills # CorvaxGoob-Skills
        skills:
        - ShuttleControl
        - Shooting

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    #gloves: ClothingHandsGlovesCaptain - Goobstation, moved to loadouts
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    - TelescopicBaton # Goobstation
    # - StationCharter

- type: chameleonOutfit
  id: CaptainChameleonOutfit
  job: Captain
  hasMindShield: true
  equipment:
    head: ClothingHeadHatCapcap
    eyes: ClothingEyesGlassesCommand
    mask: ClothingMaskGasCaptain
    neck: ClothingNeckCloakCap
