- type: job
  id: RESO
  name: job-name-RESO
  description: job-description-RESO
  playTimeTracker: JobRESO
  requirements:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 18000 #5 hrs
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 9000 #2.5 hrs
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 36000 #10 hours
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconRESO"
  supervisors: job-supervisors-captain
  canBeAntag: false
  #goobcoins: 40 #Goob content Corvax-Goob-coins
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command
  - Brig
  - Cryogenics
  - External # goobstation
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Skills # CorvaxGoob-Skills
        skills:
        - ShuttleControl

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetAltCargo # Goobstation
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
    - TelescopicBaton # Goobstation

- type: chameleonOutfit
  id: QuartermasterChameleonOutfit
  job: Quartermaster
  hasMindShield: true
  equipment:
    head: ClothingHeadHatQMsoft
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterQM
    neck: ClothingNeckCloakQm
    gloves: ClothingHandsKnuckleDustersQM
