- type: job
  id: DNIC
  name: job-name-DNIC
  description: job-description-DNIC
  playTimeTracker: JobDNIC
  requirements:
  - !type:RoleTimeRequirement
    role: JobScientist
    time: 18000 #5 hrs
  - !type:DepartmentTimeRequirement
    department: Science
    time: 36000 #10 hrs
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconDNIC"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  - External # goobstation
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Skills # CorvaxGoob-Skills
        skills:
        - AdvancedBuilding

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    ears: ClothingHeadsetAltScience # Goobstation
  storage:
    back:
    - Flash
    - TelescopicBaton # Goobstation

- type: chameleonOutfit
  id: ResearchDirectorChameleonOutfit
  job: ResearchDirector
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretRND
    eyes: ClothingEyesGlasses
    mask: ClothingMaskGas
    neck: ClothingNeckCloakRd
    outerClothing: ClothingOuterCoatRD
    gloves: ClothingHandsGlovesColorPurple
