- type: job
  id: GMS
  name: job-name-GMS
  description: job-description-GMS
  playTimeTracker: JobGMS
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 9000 #2.5 hrs
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 18000 #5 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hrs
  startingGear: CMOGear
  icon: "JobIconGMS"
  supervisors: job-supervisors-captain
  canBeAntag: false
  #goobcoins: 40 #Goob content Corvax-Goob-coins
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Brig
  - Cryogenics
  - External # goobstation
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Skills # CorvaxGoob-Skills
        skills:
        - Surgery
        - MedicalEquipment
  # Shitmed Change
  - !type:AddComponentSpecial
    components:
    - type: SurgerySpeedModifier
      speedModifier: 2
    - type: Skills # CorvaxGoob-Skills
      skills:
      - Surgery
      - MedicalEquipment

- type: startingGear
  id: CMOGear
  equipment:
    id: CMOPDA
    ears: ClothingHeadsetAltMedical # Goobstation
    eyes: ClothingEyesGlassesMed # Goobstation
    belt: ClothingBeltMedicalFilled
  storage:
    back:
    - Flash
    - TelescopicBaton # Goobstation

- type: chameleonOutfit
  id: ChiefMedicalOfficerChameleonOutfit
  job: ChiefMedicalOfficer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretCmo
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingCloakCmo
    outerClothing: ClothingOuterCoatLabCmo
    gloves: ClothingHandsGlovesNitrile
